version: 2

android_machine_ubuntu: &android_machine_ubuntu
  working_directory: ~/circleci-caver-java-android
  machine:
    image: android:202102-01
  resource_class: large

setup_android_test_files: &setup_android_test_files
  run:
    name: "Setup android instrumented test environment"
    command: |
        bash .circleci/setup_android_instrumented_test.sh

logging: &logging
  run:
    name: "Start logging example"
    command: |
      tail -f build.gradle || true
    background: true

stop_logging: &stop_logging
  run:
    name: "Stop logging"
    command: |
      kill -HUP $(pgrep -f "tail -f build.gradle")

jobs:
  android_build:
    <<: *android_machine_ubuntu
    steps:
      - checkout
      - *setup_android_test_files
      - run:
          name: "Change to Android version"
          command: |
            version=$(.circleci/version.sh)
            sed -i "s/version '.*'/version '${version}-android'/" build.gradle 
            sed -i "s/ext.web3jVersion = '.*'/ext.web3jVersion = '$web3j_version-android'/" build.gradle 
            sed -i "s/java.util.concurrent.CompletableFuture/java8.util.concurrent.CompletableFuture/" core/src/test/java/com/klaytn/caver/legacy/scenario/FastTransactionManagerIT.java

            if [ -z "$CIRCLE_TAG" ]; then
              echo "this is not RC version"
            else
              echo "trigger CIRCLE_TAG $CIRCLE_TAG"
              sed -i "s/version '.*'/version '${CIRCLE_TAG:1}-android'/" build.gradle
              sed -i "s/ext.web3jVersion = '.*'/ext.web3jVersion = '$web3j_version-android'/" build.gradle
              sed -i "s/java.util.concurrent.CompletableFuture/java8.util.concurrent.CompletableFuture/" core/src/test/java/com/klaytn/caver/legacy/scenario/FastTransactionManagerIT.java
            fi

            awk '/version '\''/' build.gradle
            awk '/ext.web3jVersion = '\''/' build.gradle
      - *logging
      - *stop_logging
workflows:
  version: 2
  workflow_build_deploy:
    jobs:
    - android_build:
        filters:
          branches:
            ignore:
              - /release\/.*/
              - master
          # tags:
          #   only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          #   only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
